version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    reviewers:
    - societe-generale/gbis-core
    assignees:
      - paul58914080
    labels:
      - dependencies
      - automated
    commit-message:
      prefix: "build: "
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    reviewers:
      - societe-generale/gbis-core
    assignees:
      - paul58914080
    labels:
      - ci
      - automated
    commit-message:
      prefix: "ci: "